
name: ci

on:
  push:
    branches:
      - fix-ci
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: [python, python3]

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        sudo apt -q -q install python3-virtualenv virtualenv
        virtualenv -p ${{matrix.python}} V
        bash -c "source ./V/bin/activate && set | egrep '^(PATH|VIRTUAL_ENV)='" >> "$GITHUB_ENV"
        echo '###' && cat "$GITHUB_ENV" && echo '###'
        echo PATH is $PATH
        which python
        python --version
        python -m pip install --upgrade pip
        python setup.py sdist
        python -m pip install dist/*
        python -m pip install mock pandas
        python -m pip install https://github.com/brandon-rhodes/assay/archive/master.zip

    - name: Test
      run: |
        bash -c "source ./V/bin/activate && set | egrep '^(PATH|VIRTUAL_ENV)='" >> "$GITHUB_ENV"
        cd ci && ../test-code.sh
